#!/bin/sh
# Vendor zstd's single-file decompressor into third-party/zstd/ for the ZIM reader.
#
# Release tarballs do not ship zstddeclib.c; it is generated by the script under
# build/single_file_libs. Pinned so device builds are reproducible; bump ZSTD_VERSION
# to update. zstd is dual-licensed BSD-3-Clause / GPLv2.
set -e

ZSTD_VERSION="1.5.6"
ZSTD_URL="https://github.com/facebook/zstd/releases/download/v$ZSTD_VERSION/zstd-$ZSTD_VERSION.tar.gz"
DEST="$(cd "$(dirname "$0")/.." && pwd)/third-party/zstd"

if ! command -v python3 >/dev/null 2>&1; then
    echo "error: need 'python3' to run zstd's amalgamation generator" >&2
    exit 1
fi

mkdir -p "$DEST"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "Fetching $ZSTD_URL"
curl -L -o "$tmp/zstd.tar.gz" "$ZSTD_URL"
tar -xzf "$tmp/zstd.tar.gz" -C "$tmp"

src="$tmp/zstd-$ZSTD_VERSION"
(cd "$src/build/single_file_libs" && ./create_single_file_decoder.sh)

cp "$src/build/single_file_libs/zstddeclib.c" "$DEST/zstddeclib.c"
cp "$src/lib/zstd.h" "$DEST/zstd.h"
cp "$src/lib/zstd_errors.h" "$DEST/zstd_errors.h" 2>/dev/null || true

echo "Vendored zstd decoder into $DEST:"
ls -la "$DEST"
